name: Email Notification on Failure

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
      repo_name:
        required: true
        type: string
    secrets:
      NOTIFICATION_EMAIL:
        required: true
      SMTP_USERNAME:
        required: true
      SMTP_PASSWORD:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world!
        
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: swapnilko@gmail.com,arunaskonde@gmail.com
          # from email name
          from: Swapnil KONDE
