name: Validate Commit Messages in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history for all branches

      - name: Fetch Base Branch
        run: |
          git fetch origin main # Ensure main branch is fetched

      - name: Validate most recent commit message
        run: |
          # Get the most recent non-merge commit
          COMMIT_MSG=$(git log --no-merges -1 --format=%s)
          
          # Check if commit message matches required format
          if ! echo "$COMMIT_MSG" | grep -qE '^ASSETMGMTA-[0-9]{4}'; then
            echo "Error: Most recent commit message does not follow the required format 'ASSETMGMTA-****'"
            echo "Found commit message: $COMMIT_MSG"
            echo "Please update your most recent commit to follow the format: ASSETMGMTA-1234"
            exit 1
          fi
          
