name: Validate Commit Messages in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history for all branches

      - name: Fetch Base Branch
        run: |
          git fetch origin main # Fetch the main branch explicitly

      - name: Validate Commit Messages
        run: |
          # Define the regex pattern for valid commit messages
          regex="^(.*: ASSETMGMTA-[0-9]+ : .*)|^.*Revert.*"

          # Get invalid commits by comparing with the main branch
          invalid_commits=$(git log --pretty=format:"%h: %s" origin/main..HEAD | grep -vE "$regex")

          if [ -n "$invalid_commits" ]; then
            echo "❌ The following commits have invalid messages:"
            echo "$invalid_commits"
            echo "Commit messages must match the format: ASSETMGMTA-***** : Commit_Message or be a Revert commit."
            exit 1
          fi

          echo "✅ All recent commit messages are valid!"
