name: Validate Commit Messages in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history for all branches

      - name: Fetch Base Branch
        run: |
          git fetch origin main # Ensure main branch is fetched

      - name: Validate Most Recent Commit
        run: |
          # Define the regex pattern for valid commit messages
          regex="^ASSETMGMTA-[0-9]+ : .+"

          # Get the most recent commit message and type
          recent_commit_message=$(git log -1 --pretty=format:"%s")
          recent_commit_type=$(git log -1 --pretty=format:"%h: %s")
          
          # Check if the most recent commit is a merge commit
          if [[ $recent_commit_message == Merge* ]]; then
            echo "✅ Skipping merge commit:"
            echo "$recent_commit_type"
            exit 0
          fi

          # Validate the recent commit message
          if [[ ! $recent_commit_message =~ $regex && ! $recent_commit_message =~ ^.*Revert.* ]]; then
            echo "❌ The most recent commit has an invalid message:"
            echo "$recent_commit_message"
            echo "Commit messages must match the format: ASSETMGMTA-***** : Commit_Message or be a Revert commit."
            exit 1
          fi

          echo "✅ The most recent commit message is valid!"
          
