name: Validate Commit Messages in PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Fetch Base Branch
        run: git fetch origin $GITHUB_BASE_REF

      - name: Validate Commit Messages
        run: |
          # Define the regex pattern for valid commit messages
          regex="^ASSETMGMT-\d+ : .+$"

          # Get the list of commits in the current pull request
          recent_commits=$(git log origin/$GITHUB_BASE_REF..HEAD --pretty=format:"%H")

          # Loop through the recent commits and validate their messages
          for commit in $recent_commits; do
            message=$(git show -s --format=%s $commit)

            if [[ ! "$message" =~ $regex ]]; then
              echo "❌ Invalid commit message: '$message'"
              echo "Commit messages must match the format: ASSETMGMT-***** : Commit_Message"
              exit 1
            fi
          done

          echo "✅ All recent commit messages are valid!"
