# .github/workflows/commit-check.yml
name: Check Commit Message Format



# Add permissions at workflow level
permissions:
  contents: read
  pull-requests: write
  issues: write
  
on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    outputs:
      invalid_messages: ${{ steps.check.outputs.invalid_messages }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Commit Messages
        id: validate
        run: |
          # Define a function to validate commit messages
          validate_message() {
            if [[ ! "$1" =~ ^ASSETMGMTA-[0-9]+ ]]; then
              echo "❌ Invalid commit message: $1"
              return 1
            fi
            return 0
          }

          INVALID_MESSAGES=""
          INVALID_COUNT=0

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Checking commits in the Pull Request..."

            # Get commits in the PR
            COMMITS=$(git log --format=%H ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

            for COMMIT in $COMMITS; do
              MESSAGE=$(git log --format=%B -n 1 $COMMIT)
              if ! validate_message "$MESSAGE"; then
                INVALID_COUNT=$((INVALID_COUNT + 1))
                INVALID_MESSAGES="${INVALID_MESSAGES}\n- ${MESSAGE}"
              fi
            done

            if [[ $INVALID_COUNT -gt 0 ]]; then
              echo "Invalid commit messages found:"
              echo -e "$INVALID_MESSAGES"
              echo "invalid_messages=${INVALID_MESSAGES}" >> $GITHUB_OUTPUT
              exit 1
            fi
          else
            echo "Not a pull request event. Skipping validation."
          fi

          echo "✅ All commit messages are valid."

      - name: Comment on PR
        if: failure() && github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ❌ This pull request contains invalid commit messages.
            
            **Invalid commit messages:**
            ${{ steps.validate.outputs.invalid_messages }}
            
            All commit messages must follow the required format:
            ```
            ASSETMGMTA-<number> <message>
            ```
            
            **Examples of valid commit messages:**
            - `ASSETMGMTA-1234 Add new feature`
            - `ASSETMGMTA-5678 Fix login bug`

            Please update your commit messages using:
            ```
            git rebase -i HEAD~<number_of_commits>
            git commit --amend -m "ASSETMGMTA-<number> <message>"
            git push --force
            ```

      - name: Fail Build
        if: failure()
        run: exit 1

# # .github/workflows/validate-commit.yml
# name: Validate Commit Messages in PR

# on:
#   workflow_call:
#     inputs:
#       config:
#         required: true
#         type: string

# jobs:
#   validate-commits:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 # Fetch full history for all branches

#       - name: Fetch Base Branch
#         run: |
#           git fetch origin main # Ensure main branch is fetched

#       - name: Validate most recent commit message
#         run: |
#           # Get the most recent non-merge commit
#           COMMIT_MSG=$(git log --no-merges -1 --format=%s)
          
#           # Check if commit message matches required format
#           if ! echo "$COMMIT_MSG" | grep -qE '^ASSETMGMTA-[0-9]+.*$'; then
#             echo "Error: Most recent commit message does not follow the required format 'ASSETMGMTA-****'"
#             echo "Found commit message: $COMMIT_MSG"
#             echo "Please update your most recent commit to follow the format: ASSETMGMTA-1234"
#             exit 1
#           fi
